server:
  port: 10000
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serverUrl:
      defaultZone: http://localhost/${server.port}/eureka/

